application: screenstitch-skeleton
version: 1
runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- channel_presence

libraries:
- name: django
  version: latest

handlers:
- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

- url: /.*
  script: djangoappengine.main.application
